new RadialGauge({
  renderTo: "gauge1",
  width: 290,
  height: 290,
  units: "Amount",
  title: false,
  value: 25,
  minValue: 0,
  maxValue: 100,
  majorTicks: ["", "", "", "80000", "", "", "", "", "", "", "389000"],
  minorTicks: 1,
  strokeTicks: false,
  highlights: [
    { from: 0, to: 25, color: "#33ff00" },
    { from: 25, to: 100, color: "#e61719" },
  ],
  colorPlate: "black",
  colorMajorTicks: "#f5f5f5",
  colorMinorTicks: "#ddd",
  colorTitle: "#fff",
  colorUnits: "yellow",
  colorNumbers: "#eee",
  colorNeedle: "#4b69a5",
  colorNeedleEnd: "#4b69a5",
  valueBox: false,
  animationRule: "bounce",
  animationDuration: 500,
}).draw();
